# Generated by Django 4.2.3 on 2023-09-07 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('UserFrom', models.IntegerField(default=-1)),
                ('isPrivate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserFrom', models.IntegerField()),
                ('Content', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserFrom', models.IntegerField(default=-1)),
                ('Content', models.CharField(max_length=200)),
                ('to_Article', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(max_length=200)),
                ('name', models.CharField(default='NULL', max_length=200)),
                ('UserFrom', models.IntegerField(default=-1)),
                ('isPrivate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('members', models.CharField(max_length=2000)),
                ('administrator', models.IntegerField(default=5)),
                ('Announcement', models.CharField(default='暂无公告！', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserFrom', models.IntegerField(default=-1)),
                ('to_Article', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=2000)),
                ('path', models.CharField(max_length=2000)),
                ('type', models.IntegerField(default=0)),
                ('subject', models.IntegerField(default=0)),
                ('grade', models.IntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=20000)),
                ('date', models.DateField(default='1970-01-01')),
                ('bilibiliCode', models.CharField(default='', max_length=20)),
                ('fullyname', models.CharField(default='unknown', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserFrom', models.IntegerField(default=-1)),
                ('Content', models.TextField(max_length=2000)),
                ('undoPlans', models.TextField(blank=True, default='', max_length=2000)),
                ('donePlans', models.TextField(blank=True, default='', max_length=2000)),
                ('linkedFile', models.CharField(default='NULL', max_length=200)),
                ('punishment', models.CharField(default='NULL', max_length=200)),
                ('Date', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 9, 2, 46, 829660))),
                ('group', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=200)),
                ('ContainsArticle', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='YingXuePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
                ('img', models.CharField(default='Li91cGxvYWQvNS82MzNjMzhhMF9FODM4NDE4X2YxZjkzNjQ4LnBuZw==', max_length=200)),
                ('groupId', models.IntegerField(default=1)),
                ('bg_url', models.CharField(default='https://cdn.luogu.com.cn/upload/image_hosting/tpp7gcqo.png', max_length=200)),
                ('font_color', models.CharField(default='white', max_length=200)),
                ('isWX', models.CharField(default='0', max_length=50)),
                ('coin', models.IntegerField(default=3)),
                ('isSuperUser', models.BooleanField(default=False)),
                ('boughtPapers', models.ManyToManyField(to='piggySQL.paper')),
            ],
        ),
    ]
