# Generated by Django 5.2.7 on 2025-11-03 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(max_length=200)),
                ('name', models.CharField(default='NULL', max_length=200)),
                ('UserFrom', models.IntegerField(default=-1)),
                ('isPrivate', models.BooleanField()),
                ('hash_code', models.CharField(default='', max_length=80)),
                ('ultimate_hash', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TreeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='族谱标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
                ('img', models.CharField(default='50269eff1afaf33db4929e2e596b0889', max_length=200)),
                ('isSuperUser', models.BooleanField(default=False)),
                ('OccupiedSpace', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='出生年份')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='去世年份')),
                ('introduction', models.TextField(blank=True, verbose_name='个人介绍')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='piggySQL.person', verbose_name='父亲')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='piggySQL.person', verbose_name='母亲')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='piggySQL.treetitle', verbose_name='所属族谱')),
            ],
        ),
        migrations.CreateModel(
            name='SpouseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage_year', models.IntegerField(blank=True, null=True, verbose_name='结婚年份')),
                ('divorce_year', models.IntegerField(blank=True, null=True, verbose_name='离婚年份')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_relations1', to='piggySQL.person', verbose_name='配偶一')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_relations2', to='piggySQL.person', verbose_name='配偶二')),
            ],
            options={
                'unique_together': {('person1', 'person2')},
            },
        ),
    ]
