# Generated by Django 4.2.3 on 2023-09-07 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 9, 10, 34, 991130)),
        ),
    ]
