# Generated by Django 5.2.7 on 2025-11-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spouserelation',
            name='divorce_year',
        ),
        migrations.RemoveField(
            model_name='spouserelation',
            name='marriage_year',
        ),
    ]
