# Generated by Django 4.2.3 on 2023-09-07 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0002_alter_plan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 9, 11, 12, 758453)),
        ),
    ]
