# Generated by Django 5.2.7 on 2025-11-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0002_remove_spouserelation_divorce_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='depth',
            field=models.IntegerField(default=0, verbose_name='深度'),
        ),
    ]
