# Generated by Django 5.2.7 on 2025-11-04 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0003_person_depth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TombHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.IntegerField(choices=[(0, '南方'), (1, '北方'), (2, '基督')], default=0, verbose_name='灵堂样式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tomb_hall', to='piggySQL.person', verbose_name='所属人员')),
            ],
        ),
        migrations.CreateModel(
            name='MemorialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='祭扫内容')),
                ('memorial_time', models.DateTimeField(auto_now_add=True, verbose_name='祭扫时间')),
                ('additional_info', models.JSONField(blank=True, default=dict, verbose_name='附加信息')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorial_records', to='piggySQL.user', verbose_name='祭扫人')),
                ('tomb_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorial_records', to='piggySQL.tombhall', verbose_name='祭扫灵堂')),
            ],
            options={
                'ordering': ['-memorial_time'],
            },
        ),
    ]
