# Generated by Django 5.2.7 on 2025-11-04 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0004_tombhall_memorialrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='piggySQL.person', verbose_name='所属人员'),
        ),
    ]
