# Generated by Django 4.2.3 on 2023-09-07 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0004_alter_plan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
