# Generated by Django 5.2.7 on 2025-11-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0005_user_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='img',
            field=models.CharField(default='50269eff1afaf33db4929e2e596b0889', max_length=200, verbose_name='图片'),
        ),
    ]
