# Generated by Django 4.2.3 on 2023-09-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0005_alter_plan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tmp',
            field=models.IntegerField(default=-1),
        ),
    ]
