# Generated by Django 4.2.3 on 2023-09-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0006_comment_tmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tmp',
        ),
    ]
