# Generated by Django 5.2.7 on 2025-11-09 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0006_person_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='手机号')),
                ('hashCode', models.CharField(max_length=100, verbose_name='编号')),
                ('verify_code', models.CharField(max_length=6, verbose_name='验证码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='uniapp_cid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='订阅时间')),
                ('last_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='最后通知时间')),
                ('tomb_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='piggySQL.tombhall', verbose_name='订阅灵堂')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='piggySQL.user', verbose_name='订阅用户')),
            ],
            options={
                'verbose_name': '用户灵堂订阅',
                'verbose_name_plural': '用户灵堂订阅',
                'unique_together': {('user', 'tomb_hall')},
            },
        ),
    ]
