# Generated by Django 4.2.3 on 2023-09-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0007_remove_comment_tmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
