# Generated by Django 5.2.7 on 2025-11-09 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0007_phoneverify_user_verified_user_uniapp_cid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='piggySQL.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户手机号关联',
                'verbose_name_plural': '用户手机号关联',
            },
        ),
    ]
