# Generated by Django 4.2.3 on 2023-09-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0008_remove_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='ContainsArticle',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.IntegerField(default=-1),
        ),
    ]
