# Generated by Django 5.2.7 on 2025-11-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0008_userphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='identificial_id',
            field=models.CharField(default='', max_length=200, verbose_name='相同ID'),
        ),
    ]
