# Generated by Django 4.2.3 on 2023-09-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0009_remove_tag_containsarticle_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='aliPath',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='paper',
            name='baiduPath',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='paper',
            name='quarkPath',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
