# Generated by Django 4.2.3 on 2023-09-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0010_paper_alipath_paper_baidupath_paper_quarkpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='path',
        ),
    ]
