# Generated by Django 5.2.7 on 2025-11-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0010_user_phone_number_alter_userphone_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tomb_hall_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='灵堂创建时间'),
        ),
        migrations.AddField(
            model_name='person',
            name='tomb_hall_style',
            field=models.IntegerField(blank=True, choices=[(0, '南方'), (1, '北方'), (2, '基督')], default=0, null=True, verbose_name='灵堂样式'),
        ),
        migrations.AddField(
            model_name='person',
            name='tomb_hall_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='灵堂更新时间'),
        ),
        migrations.DeleteModel(
            name='UserPhone',
        ),
    ]
