# Generated by Django 5.2.7 on 2025-11-13 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0011_person_tomb_hall_created_at_person_tomb_hall_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='person',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='piggySQL.person', verbose_name='订阅人员'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together={('user', 'person')},
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='tomb_hall',
        ),
    ]
