# Generated by Django 4.2.3 on 2023-09-25 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0011_remove_paper_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='administrator',
            new_name='admin',
        ),
    ]
