# Generated by Django 4.2.5 on 2023-09-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0012_rename_administrator_group_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
