# Generated by Django 5.2.7 on 2025-11-13 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0012_alter_usersubscription_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorialrecord',
            name='tomb_hall',
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together={('subscriber', 'subscribed_person')},
        ),
        migrations.AddField(
            model_name='memorialrecord',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorial_records', to='piggySQL.person'),
        ),
        migrations.AddField(
            model_name='user',
            name='card_id',
            field=models.CharField(default='Z', max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscribed_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='piggySQL.person'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscriber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='piggySQL.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memorialrecord',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='memorialrecord',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='memorialrecord',
            name='memorial_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='memorialrecord',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorial_records', to='piggySQL.user'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='piggySQL.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='identificial_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.CharField(default='50269eff1afaf33db4929e2e596b0889', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='piggySQL.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='tomb_hall_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='tomb_hall_style',
            field=models.IntegerField(blank=True, choices=[(0, '南方'), (1, '北方'), (2, '基督')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='tomb_hall_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='piggySQL.treetitle'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='phoneverify',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='phoneverify',
            name='hashCode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phoneverify',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='phoneverify',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='phoneverify',
            name='verify_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='spouserelation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spouserelation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='spouserelation',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_relations1', to='piggySQL.person'),
        ),
        migrations.AlterField(
            model_name='spouserelation',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_relations2', to='piggySQL.person'),
        ),
        migrations.AlterField(
            model_name='spouserelation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='treetitle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='treetitle',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='treetitle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='piggySQL.person'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='TombHall',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='person',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
    ]
