# Generated by Django 5.2.7 on 2025-11-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0013_remove_memorialrecord_tomb_hall_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card_id',
        ),
        migrations.AddField(
            model_name='person',
            name='card_id',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
