# Generated by Django 5.2.7 on 2025-11-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0014_remove_user_card_id_person_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='identificial_id',
        ),
    ]
