# Generated by Django 4.2.5 on 2023-12-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0014_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='UserFrom',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='bug',
            name='reply',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='user',
            name='announce_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.CharField(default='Li91cGxvYWQvMTgwOTcvV0c2QzdwWmhSeEM4ZTcyNDM3OWY1ZjJhOGVlYmVkMzI2ODhlNzQwMGRmZGIuanBn==', max_length=200),
        ),
    ]
