# Generated by Django 5.2.7 on 2025-11-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0015_remove_person_identificial_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birth_year',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='death_year',
            new_name='death_date',
        ),
    ]
