# Generated by Django 4.2.5 on 2023-12-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0016_announce'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announce',
            new_name='Message',
        ),
        migrations.RemoveField(
            model_name='user',
            name='announce_id',
        ),
        migrations.AddField(
            model_name='user',
            name='Message_id',
            field=models.IntegerField(default=0),
        ),
    ]
