# Generated by Django 4.0 on 2024-01-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0017_rename_announce_message_remove_user_announce_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='boughtPapers',
            field=models.ManyToManyField(to='piggySQL.Paper'),
        ),
    ]
