# Generated by Django 5.2.7 on 2025-11-20 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0017_add_month_day_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='treetitle',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trees', to='piggySQL.user'),
        ),
    ]
