# Generated by Django 4.0 on 2024-01-12 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0018_alter_user_boughtpapers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YingXuePlan',
        ),
    ]
