# Generated by Django 5.2.8 on 2025-12-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0019_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tomb_name',
            field=models.CharField(default='詒穀堂', max_length=50),
        ),
    ]
