# Generated by Django 4.0 on 2024-01-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0019_delete_yingxueplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hash_code',
            field=models.CharField(default='', max_length=80),
        ),
    ]
