# Generated by Django 4.0 on 2024-01-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0020_file_hash_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ultimate_hash',
            field=models.CharField(default='', max_length=80),
        ),
    ]
