# Generated by Django 5.2.8 on 2025-12-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0020_person_tomb_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tomb_bg',
            field=models.CharField(default='', max_length=200000),
        ),
    ]
