# Generated by Django 4.0 on 2024-01-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0021_file_ultimate_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.CharField(default='', max_length=32768),
        ),
    ]
