# Generated by Django 5.2.7 on 2026-01-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0021_person_tomb_bg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='father',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='person',
            name='tree',
        ),
        migrations.RemoveField(
            model_name='spouserelation',
            name='person2',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='subscribed_person',
        ),
        migrations.RemoveField(
            model_name='user',
            name='person',
        ),
        migrations.RemoveField(
            model_name='spouserelation',
            name='person1',
        ),
        migrations.AlterUniqueTogether(
            name='spouserelation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='treetitle',
            name='create_user',
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='subscriber',
        ),
        migrations.DeleteModel(
            name='MemorialRecord',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='SpouseRelation',
        ),
        migrations.DeleteModel(
            name='TreeTitle',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
