# Generated by Django 4.0 on 2024-01-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0022_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='OccupiedSpace',
            field=models.IntegerField(default=0),
        ),
    ]
