# Generated by Django 4.0 on 2024-01-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0023_user_occupiedspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bg_url',
            field=models.CharField(default='defaultBg', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.CharField(default='50269eff1afaf33db4929e2e596b0889', max_length=200),
        ),
    ]
