# Generated by Django 4.0 on 2024-01-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0024_alter_user_bg_url_alter_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bg_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='font_color',
        ),
    ]
