# Generated by Django 4.0 on 2024-01-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0025_remove_user_bg_url_remove_user_font_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groupId',
        ),
    ]
