# Generated by Django 4.0 on 2024-07-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0026_delete_group_remove_user_groupid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadVIPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=20)),
                ('expired_date', models.DateTimeField()),
            ],
        ),
    ]
