# Generated by Django 4.0 on 2024-09-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0027_padvips'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PadVIPs',
        ),
    ]
