# Generated by Django 4.0 on 2025-01-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0028_delete_padvips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='boughtPapers',
            field=models.ManyToManyField(blank=True, to='piggySQL.Paper'),
        ),
    ]
